#  ----------------------------------------------------------------------------------
#  Copyright 2020 Intel Corp.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0'
#  ----------------------------------------------------------------------------------

FROM alpine:latest

# tunneling host name or ip
ARG TUNNEL_HOST

# ssh port in use, set this number if it is not the usually port 22 
# or there is a different ssh port mapping between local and remote
ARG TUNNEL_SSH_PORT

# port number of service to forward
ARG SERVICE_PORT

# remote sshd host name or ip address for services to listen on ssh tunneling
ARG SERVICE_HOST

RUN apk add --update dumb-init openssh-client && rm -rf /var/cache/apk/*

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh \
    && ln -s /usr/local/bin/entrypoint.sh /

ENV APP_PORT=49990
EXPOSE $APP_PORT $SERVICE_PORT $TUNNEL_SSH_PORT

ENTRYPOINT ["entrypoint.sh"]
